src/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
        path('signin/', views.signin, name='signin'),
        path('signup/', views.signup, name='signup'),
        path('profile/<str:user_name>', views.profile, name='profile'),
        path('edit/', views.edit, name='edit'),
        path('logout/', views.out, name='out'),
        path('rank/<str:token>', views.rank, name='rank')
]

src/ctfs/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('<str:cat_slug>/', views.category, name='category'),
        path('<str:cat_slug>/<str:ctf_slug>', views.ctf, name='ctf')
]

src/project/urls.py
from django.views import defaults
from django.contrib import admin
from django.urls import include, re_path, path

urlpatterns = [
    path('', include('home.urls')),
    path('ctfs/', include('ctfs.urls')),
    re_path('^accounts/login/', defaults.page_not_found, {'exception': Exception()}),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('scoreboard/', include('scoreboard.urls')),
    path('dashboard/secret/admin', admin.site.urls),
]

src/accounts/models.py
from django.db import models
from django.contrib.auth import models as auth_models
from django.contrib.auth.models import timezone
from django.db.models import F, Min, Max
from secrets import token_hex

# Create your models here
class UserProfileInfo(models.Model):
    user                    =   models.OneToOneField(auth_models.User, on_delete=models.CASCADE)
    portfolio_site          =   models.URLField(blank=True)
    score                   =   models.PositiveIntegerField(default=0, db_index=True)
    last_submission_date    =   models.DateTimeField('Last Submission Date', default=timezone.now)
    token                   =   models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.user.username
    class Meta:
        ordering = ['-score', 'last_submission_date', 'user__username']
        verbose_name = 'profile'
        verbose_name_plural = 'profiles'

# Create your models here.

src/accounts/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

class UserInfosUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields=('portfolio_site',)
    def __init__(self, *args, **kwargs):
        super(UserInfosUpdateForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = False

class UserPasswordChange(forms.ModelForm):
    class Meta:
        model = User
        fields=('password',)

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields=('username', 'email',)
    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = True

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site',)

src/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django import forms
from ctfs.models import CTF_flags
from .forms import UserForm,UserProfileInfoForm, UserInfosUpdateForm, UserUpdateForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse

from secrets import token_hex
from accounts.models import UserProfileInfo

def signin(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('home'))
                else:
                    return HttpResponse("Your account was inactive.")
            else:
                return render(request, 'accounts/login.html', {'error': True})
        else:
            return render(request, 'accounts/login.html', {})
    else:
        return HttpResponseRedirect(reverse('home'))

def signup(request):
    if not request.user.is_authenticated:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        registered = False
        if request.method == 'POST':
            pass1 = request.POST.get('password')
            if len(pass1) < 8:
                return render(request,'accounts/register.html', {'user_form':user_form, 'profile_form':profile_form, 'registered_failed':"The new password must be at least %d characters long." % 8})
            first_isalpha = pass1[0].isalpha()
            if not any(c.isdigit() for c in pass1) or not any(c.isalpha() for c in pass1):
                return render(request,'accounts/register.html', {'user_form':user_form, 'profile_form':profile_form, 'registered_failed':"The password must contain at least one letter and at least one digit or punctuation character."})
            if User.objects.filter(email=request.POST.get('email')).exists():
                return render(request,'accounts/register.html', {'user_form':user_form, 'profile_form':profile_form, 'registered_failed':"A user with that email already exists."})
            user_form = UserForm(data=request.POST)
            profile_form = UserProfileInfoForm(data=request.POST)
            if user_form.is_valid() and profile_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()
                profile = profile_form.save(commit=False)
                profile.user = user
                profile.token = token_hex(16)
                profile.save()
                registered = True
            else:
                return render(request,'accounts/register.html', {'user_form':user_form, 'profile_form':profile_form, 'registered_failed':"A user with that username already exists."})
        return render(request,'accounts/register.html',
                {'user_form':user_form,
                    'profile_form':profile_form,
                    'registered':registered})
    else:
        return HttpResponseRedirect(reverse('home'))

@login_required
def out(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

@login_required
def edit(request):
    if request.method == 'POST':
        umail = request.user.email
        uuser = request.user.username
        p_form = UserInfosUpdateForm(request.POST, instance=request.user.userprofileinfo)
        u_form = UserUpdateForm(request.POST, instance=request.user)
        error = None
        success = None
        if p_form.is_valid() and u_form.is_valid():
            pmail = u_form.cleaned_data['email']
            if pmail == umail:
                pass
            else:
                if User.objects.filter(email=pmail).exists():
                    error = "Email already taken."
            puser = u_form.cleaned_data['username']
            if puser == uuser:
                pass
            else:
                if User.objects.filter(username=puser).exists():
                    error = "Username already taken."
            if error is None:
                u_form.save()
                p_form.save()
                success = "Updated."
        request.user.username = uuser
        
        context={'p_form': p_form, 'u_form': u_form, 'error':error, 'success' : success}
        return render(request, 'accounts/edit.html', context)
    else:
        p_form = UserInfosUpdateForm(instance=request.user.userprofileinfo)
        u_form = UserUpdateForm(instance=request.user)
        context={'p_form': p_form, 'u_form': u_form, 'token': request.user.userprofileinfo.token}
        return render(request, 'accounts/edit.html',context )

@login_required
def profile(request, user_name):
    user_obj = get_object_or_404(User, username=user_name)
    solves = CTF_flags.objects.filter(user=user_obj).order_by('-flag_date')
    return render(request,'accounts/profile.html', {'user':user_obj, 'solves':solves})
# Create your views here.

def rank(request, token):
    all_users      = UserProfileInfo.objects.filter(score__gt=0).select_related().order_by('-score', 'last_submission_date', 'user__username')
    
    rank = 1
    for elem in all_users:
        if elem.token == token:
            break
        rank += 1
    data = {"rank": rank}
    return JsonResponse(data)

src/accounts/templates/accounts/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
  <div class="col-sm-12 col-md-9">
    <div class="ctf-block">
		<div class="ctf-head">
			<h3>Edit info</h3>
		</div>
        <div class="bloc-body">
            <div class="col-sm-12 col-md-12 mx-auto">
				{{ u_form.non_field_errors }}
				{% if error is not None %}
					<span class="message error-msg">{{ error }}</span>
				{% elif success is not None %}
					<span class="message success-msg">{{ success }}</span>
				{% endif %}
				<form method='POST'>
                    <div class="edit-infos-grp">
						{%csrf_token%}
						<label for="{{ u_form.username.id_for_label }}">Username *</label>
						{{ u_form.username.errors}}
						{{u_form.username}}
						</br>
						<label for="{{ u_form.email.id_for_label }}">Email *</label>
						{{ u_form.email.errors}}
						{{u_form.email}}
						</br>
						</br>
						<label for="{{ p_form.portfolio_site.id_for_label }}">Website</label>
						{{p_form.portfolio_site}}
						</br>
						</br>Token
						<input type='text' readonly value='{{token}}'>
						</br>
                        <input class="form-control" type="submit" value="Save">
					</div>
				</form>
			</div>
		</div>
	</div>
  </div>
  <div class="d-none d-md-block col-10 col-md-3 right-sidebar">
    <ul class="list-group">
		<li class="list-group-item">{{ user.username }}</li>
		<li class="list-group-item">{{ user.userprofileinfo.score }} points</li>
		{% if user.userprofileinfo.portfolio_site %}
			<li class="list-group-item">
				<a href="{{ user.userprofileinfo.portfolio_site }}" target="_blank">
					{{ user.userprofileinfo.portfolio_site }}
				</a>
			</li>
		{% endif %}
		<li class="list-group-item">Member since {{ user.date_joined|date:"Y-m-d" }}</li>
	</ul>
  </div>
</div>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
        <div class="col-sm-12 col-md-9">
                <div class="ctf-block">
                        <div class="ctf-head">
                                <h3>Login</h3>
                        </div>
                        <div class="ctf-body">
                            <div class="col-sm-8 col-md-6 mx-auto">
                                    {% if error %}
                                    <span class="message error-msg">Please, verify your infos.</span>
                                    {% endif %}
                                    <form method="post">
                                            {% csrf_token %}
                                                <div class="form-group">
                                            <input class="form-control" type="text" name="username" placeholder="Username"></br>
                                            <input class="form-control" type="password" name="password" placeholder="Password"></br>
                                            <input class="form-control" type="submit" value="login">
                                        </div>
										<a href="{% url 'password_reset' %}">Reset password</a>
                                    </form>
                            </div>
                        </div>
                </div>

        </div>
        <div class="col-sm-12 col-md-3 right-sidebar">
                <ul class="list-group">
                        <a href="/accounts/signin" class="list-group-item">Login</a>
                        <a href="/accounts/signup" class="list-group-item">Sign up</a>
                </ul>
        </div>
</div>
{% endblock %}

src/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
  <div class="col-sm-12 col-md-9">
    <div>
		<h4>Challenges Solved by {{ user.username }}</h4>
			{% if solves%}
			<table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">Challenge</th>
            <th scope="col">Category</th>
            <th scope="col">Points</th>
            <th scope="col">Date</th>
          </tr>
        </thead>
        <tbody>
					{% for s in solves %}
					<tr>
						<th scope="row"><a href="/ctfs/{{ s.ctf.category.slug }}/{{ s.ctf.slug }}">{{ s.ctf.name }}</a></th>
							<td>{{ s.ctf.category.name}}</td>
							<td>{{ s.ctf.points }}</td>
							<td>{{ s.flag_date|date:"Y-m-d H:i:s" }}</td>
          </tr>
					{% endfor %}
        </tbody>
      </table>
			{% else %}
			<p>It's seem {{ user.username }} have never solved any CTF yet...</p>
			{% endif %}
    </div>
  </div>
  <div class="d-none d-md-block col-10 col-md-3 right-sidebar">
    <ul class="list-group">
		<li class="list-group-item">{{ user.username }}</li>
		<li class="list-group-item">{{ user.userprofileinfo.score }} points</li>
		{% if user.userprofileinfo.portfolio_site %}
			<li class="list-group-item">
				<a href="{{ user.userprofileinfo.portfolio_site }}" target="_blank">
					{{ user.userprofileinfo.portfolio_site }}
				</a>
			</li>
		{% endif %}
		<li class="list-group-item">Member since {{ user.date_joined|date:"Y-m-d" }}</li>
	</ul>
  </div>
</div>
{% endblock %}

src/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
        <div class="col-sm-12 col-md-9">
                <div class="ctf-block">
                        <div class="ctf-head">
                                <h3>Register</h3>
                        </div>
                        <div class="ctf-body sign-body">
                            <div class="col-sm-8 col-md-6 mx-auto">
                                {% if registered %}
                                <h1>Welcome !</h1>
                                <span class="message success-msg">Your account has been created.</span>
                                {% else %}
                                {% if registered_failed %}
                                        <span class="message error-msg">{{ registered_failed }}</span>
                                {% endif %}
                                <form enctype="multipart/form-data" method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                        <input class="form-control" type="text" name="username" placeholder="Username*" maxlength="150" required="" id="id_username"></br>
                                        <input class="form-control" type="password" name="password" placeholder="Password*" required="" id="id_password"></br>
                                        <input class="form-control" type="email" name="email" placeholder="pleasedontgivemy@private.infos*" required="" maxlength="254" id="id_email"></br>
                                        <input class="form-control" type="url" name="portfolio_site" placeholder="Personal website"maxlength="200" id="id_portfolio_site"></br>
                                        <input type="submit" name="" class="form-control" value="Register">
                                        </div>
                                </form>
                                {% endif %}
                            </div>
                        </div>
                </div>

        </div>
        <div class="col-sm-12 col-md-3 right-sidebar">
                <ul class="list-group">
                        <a href="/accounts/signup" class="list-group-item">Sign up</a>
                        <a href="/accounts/signin" class="list-group-item">Login</a>
                </ul>
        </div>
</div>
{% endblock %}